---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wordpress
  namespace: flux-system
spec:
  chart:
    spec:
      chart: wordpress
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: wordpress
  values:
    wordpressUsername: admin
    wordpressPassword: ChangeMe
    mariadb:
      auth:
        rootPassword: ChangeMe
    service:
      type: NodePort
      nodePorts.http: 30000
  interval: 1m0s
