apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wordpress
  namespace: flux-system
spec:
  chart:
    spec:
      chart: wordpress
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: wordpress
  values:
    image:
      tag: 6.4.3 # {"$imagepolicy": "flux-system:wordpress:tag"}
    wordpressUsername: admin
    wordpressPassword: ChangeMe
    mariadb:
      auth:
        rootPassword: ChangeMe
    service:
      type: NodePort
  interval: 1m0s
